CREATE DATABASE QUAN_LY_THU_VIEN
GO

USE QUAN_LY_THU_VIEN
GO

CREATE TABLE DOC_GIA (
	MaDocGia INT PRIMARY KEY IDENTITY(1,1),
	TenDocGia NVARCHAR(50),
	NgaySinh DATE,
	GioiTinh NVARCHAR(3) CHECK(GioiTinh='Nam' OR GioiTinh='Nữ'),
	SDT VARCHAR(30),
	DiaChi NVARCHAR(100)
)

CREATE TABLE NHAN_VIEN (
	MaNV INT PRIMARY KEY IDENTITY(1,1),
	TenNV NVARCHAR(50),
	NgaySinh DATE,
	GioiTinh NVARCHAR(3) CHECK(GioiTinh='Nam' OR GioiTinh='Nữ'),
	SDT VARCHAR(30),
	DiaChi NVARCHAR(100)
)

CREATE TABLE LOAI_THE (
	MaLoaiThe INT PRIMARY KEY IDENTITY(1,1),
	TenLoaiThe NVARCHAR(50),
	MucGiamGia INT
)

CREATE TABLE THE_LOAI_SACH (
	MaTheLoai INT PRIMARY KEY IDENTITY(1,1),
	TenTheLoai NVARCHAR(50),
	MoTa NTEXT
)

CREATE TABLE TAC_GIA (
	MaTacGia INT PRIMARY KEY IDENTITY(1,1),
	TenTacGia NVARCHAR(50),
	TieuSu NTEXT
)

CREATE TABLE NHA_XUAT_BAN (
	MaNXB INT PRIMARY KEY IDENTITY(1,1),
	TenNXB NVARCHAR(50),
	SDT VARCHAR(30),
	DiaChi NVARCHAR(100)
)

CREATE TABLE SACH (
	MaSach INT PRIMARY KEY IDENTITY(1,1),
	TenSach NVARCHAR(50),
	MaTheLoai INT,
	MaTacGia INT,
	MaNXB INT,
	NamXB INT,
	SoLuongSach INT,
	SLDangMuon INT,
	GiaMuon INT,
	NoiDung NTEXT,
	FOREIGN KEY (MaTheLoai) REFERENCES THE_LOAI_SACH(MaTheLoai),
	FOREIGN KEY (MaTacGia) REFERENCES TAC_GIA(MaTacGia),
	FOREIGN KEY (MaNXB) REFERENCES NHA_XUAT_BAN(MaNXB)
)

CREATE TABLE THE_TRUYEN (
	MaThe INT PRIMARY KEY IDENTITY(1,1),
	MaDocGia INT,
	MaLoaiThe INT,
	NgayCap DATE,
	NgayHetHan DATE,
	SoDu MONEY,
	FOREIGN KEY (MaDocGia) REFERENCES DOC_GIA(MaDocGia),
	FOREIGN KEY (MaLoaiThe) REFERENCES LOAI_THE(MaLoaiThe)
)

CREATE TABLE PHIEU_MUON (
	MaPhieu INT PRIMARY KEY IDENTITY(1,1),
	MaThe INT,
	MaNV INT,
	NgayMuon DATE,
	NgayHenTra DATE,
	FOREIGN KEY (MaThe) REFERENCES THE_TRUYEN(MaThe),
	FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
)

CREATE TABLE PHIEU_MUON_CHI_TIET (
	MaPhieu INT,
	MaSach INT,
	SoLuong INT,
	ThanhToan MONEY,
	NgayTra DATE,
	TienPhat MONEY,
	PRIMARY KEY (MaPhieu, MaSach),
	FOREIGN KEY (MaPhieu) REFERENCES PHIEU_MUON(MaPhieu),
	FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
)